#!/bin/sh
# carbonized-dark, a shell theme script by nightsense
# generated with a template adapted from
# Base16 Shell template by Chris Kempson (http://chriskempson.com)

if $SHELL | sed 's#.*/##' | grep '^fish$'

# set fish colours
set fish_color_autosuggestion 'd48c59'
set fish_color_command '6a9e6a'
set fish_color_comment '75746c'
set fish_color_cwd 'c9759f'
set fish_color_cwd_root 'e07070'
set fish_color_end '6a9e6a'
set fish_color_error 'e07070'
set fish_color_escape '9f80bf'
set fish_color_history_current '2b2b2b' --background='bfad51'
set fish_color_host normal
set fish_color_match 'd48c59'
set fish_color_normal normal
set fish_color_operator '659fc9'
set fish_color_param '659fc9'
set fish_color_quote '6a9e6a'
set fish_color_redirection '6a9e6a'
set fish_color_search_match '2b2b2b' --background='bfad51'
set fish_color_selection '2b2b2b' --background='e0ddce'
set fish_color_user normal
set fish_color_valid_path --underline
set fish_pager_color_completion normal
set fish_pager_color_description '75746c'
set fish_pager_color_prefix 'd48c59'
set fish_pager_color_progress 'd48c59'

sh ~/.nightshell/carbonized-dark

else

# linux console
if [ "${TERM%%-*}" = 'linux' ]; then
  echo -e "\e]P02b2b2b"
  echo -e "\e]P1e07070"
  echo -e "\e]P26a9e6a"
  echo -e "\e]P3bfad51"
  echo -e "\e]P4659fc9"
  echo -e "\e]P59f80bf"
  echo -e "\e]P65c9e93"
  echo -e "\e]P7bfbdb0"
  echo -e "\e]P875746c"
  echo -e "\e]P9d48c59"
  echo -e "\e]PA403f3d"
  echo -e "\e]PB545451"
  echo -e "\e]PC949288"
  echo -e "\e]PDe0ddce"
  echo -e "\e]PEc9759f"
  echo -e "\e]PFfffceb"
  echo -e "\e[H"
  echo -e "\e[2J"
  exit 0
fi

color00="2b/2b/2b" # Base 00 - Black
color01="e0/70/70" # Base 08 - Red
color02="6a/9e/6a" # Base 0B - Green
color03="bf/ad/51" # Base 0A - Yellow
color04="65/9f/c9" # Base 0D - Blue
color05="9f/80/bf" # Base 0E - Magenta
color06="5c/9e/93" # Base 0C - Cyan
color07="bf/bd/b0" # Base 05 - White
color08="75/74/6c" # Base 03 - Bright Black
color09="d4/8c/59" # Base 09
color10="40/3f/3d" # Base 01
color11="54/54/51" # Base 02
color12="94/92/88" # Base 04
color13="e0/dd/ce" # Base 06
color14="c9/75/9f" # Base 0F
color15="ff/fc/eb" # Base 07 - Bright White
color_foreground="bf/bd/b0" # Base 05
color_background="2b/2b/2b" # Base 00

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  printf_template='\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\'
  printf_template_var='\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\'
  printf_template_custom='\033Ptmux;\033\033]%s%s\033\033\\\033\\'
elif [ "${TERM%%-*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  printf_template='\033P\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033P\033]%d;rgb:%s\033\\'
  printf_template_custom='\033P\033]%s%s\033\\'
else
  printf_template='\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033]%d;rgb:%s\033\\'
  printf_template_custom='\033]%s%s\033\\'
fi

# 16 color space
printf $printf_template 0  $color00
printf $printf_template 1  $color01
printf $printf_template 2  $color02
printf $printf_template 3  $color03
printf $printf_template 4  $color04
printf $printf_template 5  $color05
printf $printf_template 6  $color06
printf $printf_template 7  $color07
printf $printf_template 8  $color08
printf $printf_template 9  $color09
printf $printf_template 10 $color10
printf $printf_template 11 $color11
printf $printf_template 12 $color12
printf $printf_template 13 $color13
printf $printf_template 14 $color14
printf $printf_template 15 $color15

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  printf $printf_template_custom Pg bfbdb0 # foreground
  printf $printf_template_custom Ph 2b2b2b # background
  printf $printf_template_custom Pi bfbdb0 # bold color
  printf $printf_template_custom Pj 75746c # selection color
  printf $printf_template_custom Pk e0ddce # selected text color
  printf $printf_template_custom Pl d48c59 # cursor
  printf $printf_template_custom Pm 2b2b2b # cursor text
else
  printf $printf_template_var 10 $color_foreground
  printf $printf_template_var 11 $color_background
  if [ "${TERM%%-*}" = "rxvt" ]; then
    printf $printf_template_var 708 $color_background # internal border (rxvt)
  fi
  printf $printf_template_custom 12 ";7" # cursor (reverse video)
fi

# clean up
unset printf_template
unset printf_template_var
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color_foreground
unset color_background

# set cursor colour
printf '%b' '\e]12;#d48c59\a'
