#!/bin/sh
# carbonized-light, a shell theme script by nightsense
# generated with a template adapted from
# Base16 Shell template by Chris Kempson (http://chriskempson.com)


# This script doesn't support linux console (use 'vconsole' template instead)
if [ "${TERM%%-*}" = 'linux' ]; then
  return 2>/dev/null || exit 0
fi

color00="ff/fc/eb" # Base 00 - Black
  color01="eb/3a/3a" # Base 08 - Red
  color02="25/94/2e" # Base 0B - Green
  color03="e0/bf/38" # Base 0A - Yellow
  color04="30/83/bf" # Base 0D - Blue
  color05="87/60/bf" # Base 0E - Magenta
  color06="0c/94/89" # Base 0C - Cyan
  color07="54/54/51" # Base 05 - White
  color08="94/92/88" # Base 03 - Bright Black
  color09="e0/68/12" # Base 09
  color10="e0/dd/ce" # Base 01
  color11="bf/bd/b0" # Base 02
  color12="75/74/6c" # Base 04
  color13="40/3f/3d" # Base 06
  color14="e0/5e/85" # Base 0F
  color15="2b/2b/2b" # Base 07 - Bright White
  color_foreground="54/54/51" # Base 05
  color_background="ff/fc/eb" # Base 00

  if [ -n "$TMUX" ]; then
    # Tell tmux to pass the escape sequences through
    # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
    printf_template='\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\'
    printf_template_var='\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\'
    printf_template_custom='\033Ptmux;\033\033]%s%s\033\033\\\033\\'
  elif [ "${TERM%%-*}" = "screen" ]; then
    # GNU screen (screen, screen-256color, screen-256color-bce)
    printf_template='\033P\033]4;%d;rgb:%s\033\\'
    printf_template_var='\033P\033]%d;rgb:%s\033\\'
    printf_template_custom='\033P\033]%s%s\033\\'
  else
    printf_template='\033]4;%d;rgb:%s\033\\'
    printf_template_var='\033]%d;rgb:%s\033\\'
    printf_template_custom='\033]%s%s\033\\'
  fi

  # 16 color space
  printf $printf_template 0  $color00
  printf $printf_template 1  $color01
  printf $printf_template 2  $color02
  printf $printf_template 3  $color03
  printf $printf_template 4  $color04
  printf $printf_template 5  $color05
  printf $printf_template 6  $color06
  printf $printf_template 7  $color07
  printf $printf_template 8  $color08
  printf $printf_template 9  $color09
  printf $printf_template 10 $color10
  printf $printf_template 11 $color11
  printf $printf_template 12 $color12
  printf $printf_template 13 $color13
  printf $printf_template 14 $color14
  printf $printf_template 15 $color15

  # foreground / background / cursor color
  if [ -n "$ITERM_SESSION_ID" ]; then
    # iTerm2 proprietary escape codes
    printf $printf_template_custom Pg 545451 # foreground
    printf $printf_template_custom Ph fffceb # background
    printf $printf_template_custom Pi 545451 # bold color
    printf $printf_template_custom Pj 949288 # selection color
    printf $printf_template_custom Pk 403f3d # selected text color
    printf $printf_template_custom Pl e06812 # cursor
    printf $printf_template_custom Pm fffceb # cursor text
  else
    printf $printf_template_var 10 $color_foreground
    printf $printf_template_var 11 $color_background
    if [ "${TERM%%-*}" = "rxvt" ]; then
      printf $printf_template_var 708 $color_background # internal border (rxvt)
    fi
    printf $printf_template_custom 12 ";7" # cursor (reverse video)
  fi

  # clean up
  unset printf_template
  unset printf_template_var
  unset color00
  unset color01
  unset color02
  unset color03
  unset color04
  unset color05
  unset color06
  unset color07
  unset color08
  unset color09
  unset color10
  unset color11
  unset color12
  unset color13
  unset color14
  unset color15
  unset color_foreground
  unset color_background

  printf '%b' '\e]12;#e06812\a' # set cursor colour
