#!/bin/sh
# plumber-dark, a shell theme script by nightsense
# generated with a template adapted from
# Base16 Shell template by Chris Kempson (http://chriskempson.com)


# linux console
if [ "${TERM%%-*}" = 'linux' ]; then
  echo -e "\e]P0000000"
    echo -e "\e]P1d82800"
    echo -e "\e]P200a800"
    echo -e "\e]P3fc9838"
    echo -e "\e]P45c94fc"
    echo -e "\e]P5183c5c"
    echo -e "\e]P6008088"
    echo -e "\e]P7bcbcbc"
    echo -e "\e]P8747474"
    echo -e "\e]P9c84c0c"
    echo -e "\e]PA183c5c"
    echo -e "\e]PB008088"
    echo -e "\e]PC5c94fc"
    echo -e "\e]PDbcbcbc"
    echo -e "\e]PEfc74b4"
    echo -e "\e]PFfcfcfc"
    echo -e "\e[H"
    echo -e "\e[2J"
    exit 0
  fi

  color00="00/00/00" # Base 00 - Black
    color01="d8/28/00" # Base 08 - Red
    color02="00/a8/00" # Base 0B - Green
    color03="fc/98/38" # Base 0A - Yellow
    color04="5c/94/fc" # Base 0D - Blue
    color05="18/3c/5c" # Base 0E - Magenta
    color06="00/80/88" # Base 0C - Cyan
    color07="bc/bc/bc" # Base 05 - White
    color08="74/74/74" # Base 03 - Bright Black
    color09="c8/4c/0c" # Base 09
    color10="18/3c/5c" # Base 01
    color11="00/80/88" # Base 02
    color12="5c/94/fc" # Base 04
    color13="bc/bc/bc" # Base 06
    color14="fc/74/b4" # Base 0F
    color15="fc/fc/fc" # Base 07 - Bright White
    color_foreground="bc/bc/bc" # Base 05
    color_background="00/00/00" # Base 00

    if [ -n "$TMUX" ]; then
      # Tell tmux to pass the escape sequences through
      # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
      printf_template='\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\'
      printf_template_var='\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\'
      printf_template_custom='\033Ptmux;\033\033]%s%s\033\033\\\033\\'
    elif [ "${TERM%%-*}" = "screen" ]; then
      # GNU screen (screen, screen-256color, screen-256color-bce)
      printf_template='\033P\033]4;%d;rgb:%s\033\\'
      printf_template_var='\033P\033]%d;rgb:%s\033\\'
      printf_template_custom='\033P\033]%s%s\033\\'
    else
      printf_template='\033]4;%d;rgb:%s\033\\'
      printf_template_var='\033]%d;rgb:%s\033\\'
      printf_template_custom='\033]%s%s\033\\'
    fi

    # 16 color space
    printf $printf_template 0  $color00
    printf $printf_template 1  $color01
    printf $printf_template 2  $color02
    printf $printf_template 3  $color03
    printf $printf_template 4  $color04
    printf $printf_template 5  $color05
    printf $printf_template 6  $color06
    printf $printf_template 7  $color07
    printf $printf_template 8  $color08
    printf $printf_template 9  $color09
    printf $printf_template 10 $color10
    printf $printf_template 11 $color11
    printf $printf_template 12 $color12
    printf $printf_template 13 $color13
    printf $printf_template 14 $color14
    printf $printf_template 15 $color15

    # foreground / background / cursor color
    if [ -n "$ITERM_SESSION_ID" ]; then
      # iTerm2 proprietary escape codes
      printf $printf_template_custom Pg bcbcbc # foreground
      printf $printf_template_custom Ph 000000 # background
      printf $printf_template_custom Pi bcbcbc # bold color
      printf $printf_template_custom Pj 747474 # selection color
      printf $printf_template_custom Pk bcbcbc # selected text color
      printf $printf_template_custom Pl 00a800 # cursor
      printf $printf_template_custom Pm 000000 # cursor text
    else
      printf $printf_template_var 10 $color_foreground
      printf $printf_template_var 11 $color_background
      if [ "${TERM%%-*}" = "rxvt" ]; then
        printf $printf_template_var 708 $color_background # internal border (rxvt)
      fi
      printf $printf_template_custom 12 ";7" # cursor (reverse video)
    fi

    # clean up
    unset printf_template
    unset printf_template_var
    unset color00
    unset color01
    unset color02
    unset color03
    unset color04
    unset color05
    unset color06
    unset color07
    unset color08
    unset color09
    unset color10
    unset color11
    unset color12
    unset color13
    unset color14
    unset color15
    unset color_foreground
    unset color_background

    printf '%b' '\e]12;#00a800\a' # set cursor colour
