#!/bin/sh
# nemo-light, a fish shell theme by nightsense

set fish_color_autosuggestion 'eb6200'
set fish_color_command '009e00'
set fish_color_comment '616675'
set fish_color_cwd 'eb4d9c'
set fish_color_cwd_root 'f53d3d'
set fish_color_end '009e00'
set fish_color_error 'f53d3d'
set fish_color_escape '964be0'
set fish_color_history_current 'ebf0ff' --background='ebca28'
set fish_color_host normal
set fish_color_match 'eb6200'
set fish_color_normal normal
set fish_color_operator '0083e0'
set fish_color_param '0083e0'
set fish_color_quote '009e00'
set fish_color_redirection '009e00'
set fish_color_search_match 'ebf0ff' --background='ebca28'
set fish_color_selection '161b2b' --background='bac4e0'
set fish_color_user normal
set fish_color_valid_path --underline
set fish_pager_color_completion normal
set fish_pager_color_description '616675'
set fish_pager_color_prefix 'eb6200'
set fish_pager_color_progress 'eb6200'
