#!/bin/sh
# plumber-dark, a fish shell theme by nightsense

set fish_color_autosuggestion 'c84c0c'
set fish_color_command '00a800'
set fish_color_comment '747474'
set fish_color_cwd 'fc74b4'
set fish_color_cwd_root 'd82800'
set fish_color_end '00a800'
set fish_color_error 'd82800'
set fish_color_escape '183c5c'
set fish_color_history_current '000000' --background='fc9838'
set fish_color_host normal
set fish_color_match 'c84c0c'
set fish_color_normal normal
set fish_color_operator '5c94fc'
set fish_color_param '5c94fc'
set fish_color_quote '00a800'
set fish_color_redirection '00a800'
set fish_color_search_match '000000' --background='fc9838'
set fish_color_selection '000000' --background='bcbcbc'
set fish_color_user normal
set fish_color_valid_path --underline
set fish_pager_color_completion normal
set fish_pager_color_description '747474'
set fish_pager_color_prefix 'c84c0c'
set fish_pager_color_progress 'c84c0c'
